In [1]:
import pandas as pd
df = pd.read_csv(r"E:\SET Project II\Data\Power comsumption\household_power_consumption.txt", sep=";")
print(df.head())

         Date      Time Global_active_power Global_reactive_power  Voltage  \
0  16/12/2006  17:24:00               4.216                 0.418  234.840
1  16/12/2006  17:25:00               5.360                 0.436  233.630
2  16/12/2006  17:26:00               5.374                 0.498  233.290
3  16/12/2006  17:27:00               5.388                 0.502  233.740
4  16/12/2006  17:28:00               3.666                 0.528  235.680

  Global_intensity Sub_metering_1 Sub_metering_2  Sub_metering_3
0           18.400          0.000          1.000            17.0
1           23.000          0.000          1.000            16.0
2           23.000          0.000          2.000            17.0
3           23.000          0.000          1.000            17.0
4           15.800          0.000          1.000            17.0

C:\Users\sabar\AppData\Local\Temp\ipykernel_28468\563948147.py:2: DtypeWarning: Columns (2,3,4,5,6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"E:\SET Project II\Data\Power comsumption\household_power_consumption.txt", sep=";")

In [2]:
df.isnull().sum()
(df.isnull().sum() / len(df)) * 100

Date                     0.000000
Time                     0.000000
Global_active_power      0.000000
Global_reactive_power    0.000000
Voltage                  0.000000
Global_intensity         0.000000
Sub_metering_1           0.000000
Sub_metering_2           0.000000
Sub_metering_3           1.251844
dtype: float64

In [3]:

#replace empty strings, "NA", "null", and "?" with pd.NA
df.replace(["", "NA", "null","?"], pd.NA, inplace=True)
df.isnull().sum()

Date                         0
Time                         0
Global_active_power      25979
Global_reactive_power    25979
Voltage                  25979
Global_intensity         25979
Sub_metering_1           25979
Sub_metering_2           25979
Sub_metering_3           25979
dtype: int64

In [4]:
#drop rows with missing values  
print("Before:", df.shape)
data = df.dropna()
print("After:", data.shape)
print("percent of data lost:", (1 - (len(data) / len(df))) * 100.00)

Before: (2075259, 9)
After: (2049280, 9)
percent of data lost: 1.2518437457685994

In [5]:
print(data.dtypes)
# convert columns to numeric, errors='ignore' will keep non-numeric values as is
data = data.apply(pd.to_numeric,errors='ignore')

Date                      object
Time                      object
Global_active_power       object
Global_reactive_power     object
Voltage                   object
Global_intensity          object
Sub_metering_1            object
Sub_metering_2            object
Sub_metering_3           float64
dtype: object

C:\Users\sabar\AppData\Local\Temp\ipykernel_28468\2898262299.py:3: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  data = data.apply(pd.to_numeric,errors='ignore')

In [6]:
print(data.dtypes)

Date                      object
Time                      object
Global_active_power      float64
Global_reactive_power    float64
Voltage                  float64
Global_intensity         float64
Sub_metering_1           float64
Sub_metering_2           float64
Sub_metering_3           float64
dtype: object

In [7]:
data.head()

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
0,16/12/2006,17:24:00,4.216,0.418,234.84,18.4,0.0,1.0,17.0
1,16/12/2006,17:25:00,5.360,0.436,233.63,23.0,0.0,1.0,16.0
2,16/12/2006,17:26:00,5.374,0.498,233.29,23.0,0.0,2.0,17.0
3,16/12/2006,17:27:00,5.388,0.502,233.74,23.0,0.0,1.0,17.0
4,16/12/2006,17:28:00,3.666,0.528,235.68,15.8,0.0,1.0,17.0

In [8]:
#merge date and time columns to create a datetime column
data["Date"] = pd.to_datetime(data["Date"], format=r"%d/%m/%Y", errors="coerce")
data["Time"] = pd.to_datetime(data["Time"], format=r"%H:%M:%S", errors="coerce").dt.time
data["datetime"] = pd.to_datetime(
    data["Date"].astype(str) + " " + data["Time"].astype(str),
    errors="ignore"
)
print(data.dtypes)

Date                     datetime64[ns]
Time                             object
Global_active_power             float64
Global_reactive_power           float64
Voltage                         float64
Global_intensity                float64
Sub_metering_1                  float64
Sub_metering_2                  float64
Sub_metering_3                  float64
datetime                 datetime64[ns]
dtype: object

C:\Users\sabar\AppData\Local\Temp\ipykernel_28468\1100988383.py:4: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  data["datetime"] = pd.to_datetime(

In [9]:
data.head()

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3,datetime
0,2006-12-16,17:24:00,4.216,0.418,234.84,18.4,0.0,1.0,17.0,2006-12-16 17:24:00
1,2006-12-16,17:25:00,5.360,0.436,233.63,23.0,0.0,1.0,16.0,2006-12-16 17:25:00
2,2006-12-16,17:26:00,5.374,0.498,233.29,23.0,0.0,2.0,17.0,2006-12-16 17:26:00
3,2006-12-16,17:27:00,5.388,0.502,233.74,23.0,0.0,1.0,17.0,2006-12-16 17:27:00
4,2006-12-16,17:28:00,3.666,0.528,235.68,15.8,0.0,1.0,17.0,2006-12-16 17:28:00

In [10]:
data = data.drop(['Date', 'Time'], axis=1)
data.head()

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3,datetime
0,4.216,0.418,234.84,18.4,0.0,1.0,17.0,2006-12-16 17:24:00
1,5.360,0.436,233.63,23.0,0.0,1.0,16.0,2006-12-16 17:25:00
2,5.374,0.498,233.29,23.0,0.0,2.0,17.0,2006-12-16 17:26:00
3,5.388,0.502,233.74,23.0,0.0,1.0,17.0,2006-12-16 17:27:00
4,3.666,0.528,235.68,15.8,0.0,1.0,17.0,2006-12-16 17:28:00

In [11]:
# convert minutely data to hourly data
data = data.set_index('datetime')
data = data.sort_index()
data = data.resample('h').mean()
print(data.isnull().sum())

Global_active_power      421
Global_reactive_power    421
Voltage                  421
Global_intensity         421
Sub_metering_1           421
Sub_metering_2           421
Sub_metering_3           421
dtype: int64

In [12]:
# fill missing values with forward fill method
data = data.ffill()
print(data.isnull().sum())

Global_active_power      0
Global_reactive_power    0
Voltage                  0
Global_intensity         0
Sub_metering_1           0
Sub_metering_2           0
Sub_metering_3           0
dtype: int64

In [13]:
# extract date features
data['hour'] = data.index.hour
data['day'] = data.index.day
data['month'] = data.index.month
data['weekday'] = data.index.weekday

In [14]:
# create lag features
data['lag_1'] = data['Global_active_power'].shift(1)
data['lag_2'] = data['Global_active_power'].shift(2)
data['lag_24'] = data['Global_active_power'].shift(24)

In [15]:
print(data.info())
print(data.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 34589 entries, 2006-12-16 17:00:00 to 2010-11-26 21:00:00
Freq: h
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Global_active_power    34589 non-null  float64
 1   Global_reactive_power  34589 non-null  float64
 2   Voltage                34589 non-null  float64
 3   Global_intensity       34589 non-null  float64
 4   Sub_metering_1         34589 non-null  float64
 5   Sub_metering_2         34589 non-null  float64
 6   Sub_metering_3         34589 non-null  float64
 7   hour                   34589 non-null  int32
 8   day                    34589 non-null  int32
 9   month                  34589 non-null  int32
 10  weekday                34589 non-null  int32
 11  lag_1                  34588 non-null  float64
 12  lag_2                  34587 non-null  float64
 13  lag_24                 34565 non-null  float64
dtypes: float64(10), int32(4)
memory usage: 3.4 MB
None
Global_active_power       0
Global_reactive_power     0
Voltage                   0
Global_intensity          0
Sub_metering_1            0
Sub_metering_2            0
Sub_metering_3            0
hour                      0
day                       0
month                     0
weekday                   0
lag_1                     1
lag_2                     2
lag_24                   24
dtype: int64

In [16]:
data = data.dropna()
print(data.info())
print(data.head())

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 34565 entries, 2006-12-17 17:00:00 to 2010-11-26 21:00:00
Freq: h
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Global_active_power    34565 non-null  float64
 1   Global_reactive_power  34565 non-null  float64
 2   Voltage                34565 non-null  float64
 3   Global_intensity       34565 non-null  float64
 4   Sub_metering_1         34565 non-null  float64
 5   Sub_metering_2         34565 non-null  float64
 6   Sub_metering_3         34565 non-null  float64
 7   hour                   34565 non-null  int32
 8   day                    34565 non-null  int32
 9   month                  34565 non-null  int32
 10  weekday                34565 non-null  int32
 11  lag_1                  34565 non-null  float64
 12  lag_2                  34565 non-null  float64
 13  lag_24                 34565 non-null  float64
dtypes: float64(10), int32(4)
memory usage: 3.4 MB
None
                     Global_active_power  Global_reactive_power     Voltage  \
datetime
2006-12-17 17:00:00             3.406767               0.166633  234.229833
2006-12-17 18:00:00             3.697100               0.135067  234.372333
2006-12-17 19:00:00             2.908400               0.265167  233.195667
2006-12-17 20:00:00             3.361500               0.271500  236.426500
2006-12-17 21:00:00             3.040767               0.267967  239.104167

                     Global_intensity  Sub_metering_1  Sub_metering_2  \
datetime
2006-12-17 17:00:00         14.510000             0.0        0.466667
2006-12-17 18:00:00         15.750000             0.0        0.000000
2006-12-17 19:00:00         12.516667             0.0        0.516667
2006-12-17 20:00:00         14.276667             0.0        1.116667
2006-12-17 21:00:00         12.716667             0.0        1.200000

                     Sub_metering_3  hour  day  month  weekday     lag_1  \
datetime
2006-12-17 17:00:00       16.816667    17   17     12        6  3.326033
2006-12-17 18:00:00       16.833333    18   17     12        6  3.406767
2006-12-17 19:00:00       16.683333    19   17     12        6  3.697100
2006-12-17 20:00:00       17.116667    20   17     12        6  2.908400
2006-12-17 21:00:00       17.500000    21   17     12        6  3.361500

                        lag_2    lag_24
datetime
2006-12-17 17:00:00  2.985400  4.222889
2006-12-17 18:00:00  3.326033  3.632200
2006-12-17 19:00:00  3.406767  3.400233
2006-12-17 20:00:00  3.697100  3.268567
2006-12-17 21:00:00  2.908400  3.056467

In [17]:
# create rolling mean features
data['rolling_mean_3'] = data['Global_active_power'].shift(1).rolling(3).mean()
data['rolling_mean_24'] = data['Global_active_power'].shift(1).rolling(24).mean()
data = data.dropna()

In [18]:
print(data.head())
print(data.info())

                     Global_active_power  Global_reactive_power     Voltage  \
datetime
2006-12-18 17:00:00             2.154900               0.097800  238.729167
2006-12-18 18:00:00             2.402533               0.079100  236.668500
2006-12-18 19:00:00             2.614500               0.200767  235.329167
2006-12-18 20:00:00             3.050567               0.120367  234.524333
2006-12-18 21:00:00             2.169733               0.071733  237.590833

                     Global_intensity  Sub_metering_1  Sub_metering_2  \
datetime
2006-12-18 17:00:00          8.993333             0.0        0.333333
2006-12-18 18:00:00         10.083333             0.0        0.250000
2006-12-18 19:00:00         11.190000             0.0        9.100000
2006-12-18 20:00:00         13.046667             0.0        0.500000
2006-12-18 21:00:00          9.240000             0.0        0.000000

                     Sub_metering_3  hour  day  month  weekday     lag_1  \
datetime
2006-12-18 17:00:00       17.450000    17   18     12        0  1.949300
2006-12-18 18:00:00       16.916667    18   18     12        0  2.154900
2006-12-18 19:00:00        0.000000    19   18     12        0  2.402533
2006-12-18 20:00:00       13.250000    20   18     12        0  2.614500
2006-12-18 21:00:00        3.716667    21   18     12        0  3.050567

                        lag_2    lag_24  rolling_mean_3  rolling_mean_24
datetime
2006-12-18 17:00:00  1.784300  3.406767        1.822211         1.642600
2006-12-18 18:00:00  1.949300  3.697100        1.962833         1.590439
2006-12-18 19:00:00  2.154900  2.908400        2.168911         1.536499
2006-12-18 20:00:00  2.402533  3.361500        2.390644         1.524253
2006-12-18 21:00:00  2.614500  3.040767        2.689200         1.511297
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 34541 entries, 2006-12-18 17:00:00 to 2010-11-26 21:00:00
Freq: h
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Global_active_power    34541 non-null  float64
 1   Global_reactive_power  34541 non-null  float64
 2   Voltage                34541 non-null  float64
 3   Global_intensity       34541 non-null  float64
 4   Sub_metering_1         34541 non-null  float64
 5   Sub_metering_2         34541 non-null  float64
 6   Sub_metering_3         34541 non-null  float64
 7   hour                   34541 non-null  int32
 8   day                    34541 non-null  int32
 9   month                  34541 non-null  int32
 10  weekday                34541 non-null  int32
 11  lag_1                  34541 non-null  float64
 12  lag_2                  34541 non-null  float64
 13  lag_24                 34541 non-null  float64
 14  rolling_mean_3         34541 non-null  float64
 15  rolling_mean_24        34541 non-null  float64
dtypes: float64(12), int32(4)
memory usage: 4.0 MB
None

In [19]:
data = data.reset_index(drop=False)
data.to_csv(r"E:\SET Project II\Cleaned_data.csv", index=False)

In [20]:
data.columns

Index(['datetime', 'Global_active_power', 'Global_reactive_power', 'Voltage',
       'Global_intensity', 'Sub_metering_1', 'Sub_metering_2',
       'Sub_metering_3', 'hour', 'day', 'month', 'weekday', 'lag_1', 'lag_2',
       'lag_24', 'rolling_mean_3', 'rolling_mean_24'],
      dtype='object')

In [21]:
print(data.index.name)
print(data.columns.tolist())
print(data.head())

None
['datetime', 'Global_active_power', 'Global_reactive_power', 'Voltage', 'Global_intensity', 'Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3', 'hour', 'day', 'month', 'weekday', 'lag_1', 'lag_2', 'lag_24', 'rolling_mean_3', 'rolling_mean_24']
             datetime  Global_active_power  Global_reactive_power     Voltage  \
0 2006-12-18 17:00:00             2.154900               0.097800  238.729167
1 2006-12-18 18:00:00             2.402533               0.079100  236.668500
2 2006-12-18 19:00:00             2.614500               0.200767  235.329167
3 2006-12-18 20:00:00             3.050567               0.120367  234.524333
4 2006-12-18 21:00:00             2.169733               0.071733  237.590833

   Global_intensity  Sub_metering_1  Sub_metering_2  Sub_metering_3  hour  \
0          8.993333             0.0        0.333333       17.450000    17
1         10.083333             0.0        0.250000       16.916667    18
2         11.190000             0.0        9.100000        0.000000    19
3         13.046667             0.0        0.500000       13.250000    20
4          9.240000             0.0        0.000000        3.716667    21

   day  month  weekday     lag_1     lag_2    lag_24  rolling_mean_3  \
0   18     12        0  1.949300  1.784300  3.406767        1.822211
1   18     12        0  2.154900  1.949300  3.697100        1.962833
2   18     12        0  2.402533  2.154900  2.908400        2.168911
3   18     12        0  2.614500  2.402533  3.361500        2.390644
4   18     12        0  3.050567  2.614500  3.040767        2.689200

   rolling_mean_24
0         1.642600
1         1.590439
2         1.536499
3         1.524253
4         1.511297

In [22]:
data.isnull().sum()

datetime                 0
Global_active_power      0
Global_reactive_power    0
Voltage                  0
Global_intensity         0
Sub_metering_1           0
Sub_metering_2           0
Sub_metering_3           0
hour                     0
day                      0
month                    0
weekday                  0
lag_1                    0
lag_2                    0
lag_24                   0
rolling_mean_3           0
rolling_mean_24          0
dtype: int64